config/routes.rb
ProjetDawin::Application.routes.draw do

  resources :posts
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
end

app/models/auteur.rb
class Auteur < ActiveRecord::Base

	def to_s
		"Nom : #{self.nom}
		Prenom : #{self.prenom}
		Email : #{self.email}"
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def show
		@post = Post.find(params[:id])
		@user = User.find(@post.user_id)
	end

	def create
		post = params[:post]
		post = post.permit(:titre, :datepublication, :chapeau, :contenu, :image, :user_id)

		@post = Post.new post

		if @post.save
			redirect_to [@post]
		else
			render 'new'
		end
	end

	def destroy
		post = Post.find(params[:id])

		post.delete

		redirect_to "/"
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update 
		@post = Post.find(params[:id])

		post = params[:post]
		post = post.permit(:titre, :datepublication, :chapeau, :contenu, :image, :user_id)

		if @post.update_attributes(post)
			redirect_to [@post]
		else 
			render "edit"
		end
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:user).permit(:nom, :prenom, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:nom, :prenom, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1
	Liste des postes :
%ul.list-group
	- Post.all.each do |post|
		%li.list-group-item
			.row
				.col-md-2= post.image
			.row
				.col-md-1= link_to "Detail", [post], class: "btn-primary btn"
				.col-md-2= post.titre
			.row
				.col-md-2= post.datepublication
			.row
				.col-md-12= post.chapeau
			.row
				.col-md-12= post.contenu
			.row
				.col-md-1= User.find(post.user_id).nom
				.col-md-1= User.find(post.user_id).prenom
			- if user_signed_in?
				- if current_user.id == post.user_id
					= link_to "Supprimer", post_path(post.id), :method => :delete, class: "btn-danger btn"
					= link_to "Editer", edit_post_path(post.id), class: "btn-primary btn"

- if user_signed_in?
	= link_to "Ajouter un poste", new_post_path, class: "btn-primary btn"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetDawin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
	<div class="col-md-12 text-center">
<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn-primary btn' %> |
	<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn-danger btn'  %>
<% else %>
	<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link btn-primary btn'  %> |
	<%= link_to "Login", new_user_session_path, :class => 'navbar-link btn-primary btn'  %>
<% end %>
	</div>
</div>
<%= yield %>
</body>
</html>

app/views/posts/edit.html.haml
= form_for @post do |f|
	%h1
		Modifier ce post :
	.row
		.col-md-1 titre : 
		.col-md-5= f.text_field :titre
	.row
		.col-md-1 chapeau :
		.col-md-5= f.text_field :chapeau
	.row
		.col-md-1 contenu :
	.row
		.col-md-12= f.text_area :contenu, :rows => 20, :cols => 100


	= f.submit "Modifier le post", class: "btn-success btn"
	= link_to "Retour liste post", "/", class: "btn-primary btn"

app/views/posts/index.html.haml
%h1
	Liste des postes :
%ul
	- Post.all.each do |post|
		%li
			= post.titre
			= post.datepublication
			= post.chapeau
			= post.image
			= link_to "Supprimer", post_path(post.id), :method => :delete, class: "btn-danger btn"
			= link_to "Editer", edit_post_path(post.id), class: "btn-primary btn"

= link_to "Ajouter un poste", new_post_path, class: "btn-primary btn"

app/views/posts/new.html.haml
= form_for Post.new do |f|
	%h1
		Ajouter un post :
	.row
		.col-md-1 titre : 
		.col-md-5= f.text_field :titre
	.row
		.col-md-1 chapeau :
		.col-md-5= f.text_field :chapeau
	.row
		.col-md-1 contenu :
	.row
		.col-md-12= f.text_area :contenu, :rows => 20, :cols => 100
	.row
		.col-md-12= f.file_field :image

	= f.hidden_field :datepublication, value: Time.new.to_s
	= f.hidden_field :user_id, value: current_user.id

	= f.submit "Ajouter ce post", class: "btn-success btn"
	= link_to "Retour liste post", "/", class: "btn-primary btn"

app/views/posts/show.html.haml
.row
	.col-md-12= @post.image
.row
	.col-md-12= @post.titre
.row
	.col-md-12= @post.datepublication
.row
	.col-md-12= @post.chapeau
.row
	.col-md-12= @post.contenu
.row
	.col-md-1 Auteur :
	.col-md-1= @user.nom 
	.col-md-1= @user.prenom

= link_to "Retour liste post", "/", class: "btn-primary btn"